-- 🎀 STICKER ARCHIVE: THƯ VIỆN BIỂU CẢM TIẾT KIÊM --

-- 1. Create Stickers Table (Nếu chưa có)
CREATE TABLE IF NOT EXISTS public.stickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Realtime for Stickers (Bỏ qua nếu bị lỗi 42710)
-- ALTER PUBLICATION supabase_realtime ADD TABLE stickers;

-- 3. Set up Row Level Security
ALTER TABLE public.stickers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can view stickers." ON public.stickers;
DROP POLICY IF EXISTS "Owners can insert their own stickers." ON public.stickers;
DROP POLICY IF EXISTS "Owners can delete their own stickers." ON public.stickers;

-- Cho phép mọi người xem nhãn dán (để chia sẻ niềm vui)
CREATE POLICY "Everyone can view stickers." ON public.stickers
  FOR SELECT USING (true);

-- Chỉ chủ nhân mới được thêm nhãn dán của mình
CREATE POLICY "Owners can insert their own stickers." ON public.stickers
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Chỉ chủ nhân mới được xóa nhãn dán của mình
CREATE POLICY "Owners can delete their own stickers." ON public.stickers
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- -------------------------------------------------------------
-- 💬 MESSAGE REACTIONS: BÀY TỎ CẢM XÚC CHO TỪNG TIN NHẮN
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.message_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id UUID REFERENCES public.messages(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  emoji TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT message_reactions_message_user_emoji_unique UNIQUE (message_id, user_id, emoji)
);

ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view message reactions." ON public.message_reactions;
DROP POLICY IF EXISTS "Authenticated users can insert own reactions." ON public.message_reactions;
DROP POLICY IF EXISTS "Authenticated users can delete own reactions." ON public.message_reactions;

CREATE POLICY "Authenticated users can view message reactions." ON public.message_reactions
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert own reactions." ON public.message_reactions
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Authenticated users can delete own reactions." ON public.message_reactions
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
