-- 🎀 STICKER ARCHIVE: THƯ VIỆN BIỂU CẢM TIẾT KIÊM --

-- 1. Create Stickers Table (Nếu chưa có)
CREATE TABLE IF NOT EXISTS public.stickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Realtime for Stickers (Bỏ qua nếu bị lỗi 42710)
-- ALTER PUBLICATION supabase_realtime ADD TABLE stickers;

-- 3. Set up Row Level Security
ALTER TABLE public.stickers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can view stickers." ON public.stickers;
DROP POLICY IF EXISTS "Owners can insert their own stickers." ON public.stickers;
DROP POLICY IF EXISTS "Owners can delete their own stickers." ON public.stickers;

-- Cho phép mọi người xem nhãn dán (để chia sẻ niềm vui)
CREATE POLICY "Everyone can view stickers." ON public.stickers
  FOR SELECT USING (true);

-- Chỉ chủ nhân mới được thêm nhãn dán của mình
CREATE POLICY "Owners can insert their own stickers." ON public.stickers
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Chỉ chủ nhân mới được xóa nhãn dán của mình
CREATE POLICY "Owners can delete their own stickers." ON public.stickers
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- -------------------------------------------------------------
-- 🧱 MESSAGE SCHEMA HARDENING: ĐẢM BẢO LƯU ĐƯỢC EFFECT (textsize)
-- -------------------------------------------------------------
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS effect TEXT NOT NULL DEFAULT 'none';

ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS is_opened BOOLEAN NOT NULL DEFAULT FALSE;

-- -------------------------------------------------------------
-- 💬 MESSAGE REACTIONS: BÀY TỎ CẢM XÚC CHO TỪNG TIN NHẮN
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.message_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id UUID REFERENCES public.messages(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL,
  emoji TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT message_reactions_message_user_emoji_unique UNIQUE (message_id, user_id, emoji)
);

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.message_reactions;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_object THEN NULL;
END $$;

ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view message reactions." ON public.message_reactions;
DROP POLICY IF EXISTS "Authenticated users can insert own reactions." ON public.message_reactions;
DROP POLICY IF EXISTS "Authenticated users can delete own reactions." ON public.message_reactions;

CREATE POLICY "Authenticated users can view message reactions." ON public.message_reactions
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert own reactions." ON public.message_reactions
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Authenticated users can delete own reactions." ON public.message_reactions
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- -------------------------------------------------------------
-- 🗑️ MESSAGE DELETE REQUESTS: XIN CHẤP NHẬN TRƯỚC KHI XÓA
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.message_delete_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id UUID REFERENCES public.messages(id) ON DELETE CASCADE NOT NULL,
  requester_id UUID REFERENCES auth.users NOT NULL,
  approver_id UUID REFERENCES auth.users NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  responded_at TIMESTAMP WITH TIME ZONE
);

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.message_delete_requests;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS message_delete_requests_pending_unique
  ON public.message_delete_requests(message_id)
  WHERE status = 'pending';

ALTER TABLE public.message_delete_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own delete requests." ON public.message_delete_requests;
DROP POLICY IF EXISTS "Requester can create delete request." ON public.message_delete_requests;
DROP POLICY IF EXISTS "Approver can respond delete request." ON public.message_delete_requests;
DROP POLICY IF EXISTS "Requester can cancel own pending request." ON public.message_delete_requests;

CREATE POLICY "Users can view own delete requests." ON public.message_delete_requests
  FOR SELECT TO authenticated
  USING (auth.uid() = requester_id OR auth.uid() = approver_id);

CREATE POLICY "Requester can create delete request." ON public.message_delete_requests
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = requester_id);

CREATE POLICY "Approver can respond delete request." ON public.message_delete_requests
  FOR UPDATE TO authenticated
  USING (auth.uid() = approver_id)
  WITH CHECK (auth.uid() = approver_id);

CREATE POLICY "Requester can cancel own pending request." ON public.message_delete_requests
  FOR DELETE TO authenticated
  USING (auth.uid() = requester_id AND status = 'pending');

-- -------------------------------------------------------------
-- ✅ MESSAGE DELETE EXECUTION: CHO PHÉP XÓA SAU KHI ĐƯỢC DUYỆT
-- -------------------------------------------------------------
DROP POLICY IF EXISTS "Users can delete approved messages." ON public.messages;

CREATE POLICY "Users can delete approved messages." ON public.messages
  FOR DELETE TO authenticated
  USING (
    auth.uid() = sender_id
    OR EXISTS (
      SELECT 1
      FROM public.message_delete_requests mdr
      WHERE mdr.message_id = messages.id
        AND mdr.approver_id = auth.uid()
        AND mdr.status = 'accepted'
    )
  );

-- -------------------------------------------------------------
-- 🔥 LOVE STREAKS: LƯU CHUỖI THAY VÌ QUÉT TOÀN BỘ TIN NHẮN
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.love_streaks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_low UUID REFERENCES auth.users NOT NULL,
  user_high UUID REFERENCES auth.users NOT NULL,
  current_streak INTEGER NOT NULL DEFAULT 0,
  longest_streak INTEGER NOT NULL DEFAULT 0,
  last_mutual_day DATE,
  today_day DATE,
  today_has_low BOOLEAN NOT NULL DEFAULT FALSE,
  today_has_high BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT love_streaks_pair_unique UNIQUE (user_low, user_high),
  CONSTRAINT love_streaks_pair_check CHECK (user_low <> user_high)
);

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.love_streaks;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_object THEN NULL;
END $$;

ALTER TABLE public.love_streaks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own love streak rows." ON public.love_streaks;
DROP POLICY IF EXISTS "Users can insert own love streak rows." ON public.love_streaks;
DROP POLICY IF EXISTS "Users can update own love streak rows." ON public.love_streaks;

CREATE POLICY "Users can view own love streak rows." ON public.love_streaks
  FOR SELECT TO authenticated
  USING (auth.uid() = user_low OR auth.uid() = user_high);

CREATE POLICY "Users can insert own love streak rows." ON public.love_streaks
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_low OR auth.uid() = user_high);

CREATE POLICY "Users can update own love streak rows." ON public.love_streaks
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_low OR auth.uid() = user_high)
  WITH CHECK (auth.uid() = user_low OR auth.uid() = user_high);

CREATE OR REPLACE FUNCTION public.bump_love_streak_from_message()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_low UUID;
  v_high UUID;
  v_msg_day DATE;
  v_row public.love_streaks%ROWTYPE;
  v_today_low BOOLEAN;
  v_today_high BOOLEAN;
  v_new_streak INTEGER;
BEGIN
  IF NEW.sender_id IS NULL OR NEW.receiver_id IS NULL OR NEW.sender_id = NEW.receiver_id THEN
    RETURN NEW;
  END IF;

  IF NEW.sender_id::text < NEW.receiver_id::text THEN
    v_low := NEW.sender_id;
    v_high := NEW.receiver_id;
  ELSE
    v_low := NEW.receiver_id;
    v_high := NEW.sender_id;
  END IF;

  v_msg_day := (NEW.created_at AT TIME ZONE 'utc')::date;

  INSERT INTO public.love_streaks (user_low, user_high, today_day, updated_at)
  VALUES (v_low, v_high, v_msg_day, timezone('utc'::text, now()))
  ON CONFLICT (user_low, user_high) DO NOTHING;

  SELECT *
  INTO v_row
  FROM public.love_streaks
  WHERE user_low = v_low AND user_high = v_high
  FOR UPDATE;

  IF v_row.today_day IS NULL OR v_row.today_day < v_msg_day THEN
    v_row.today_day := v_msg_day;
    v_row.today_has_low := FALSE;
    v_row.today_has_high := FALSE;
  END IF;

  IF NEW.sender_id = v_low THEN
    v_today_low := TRUE;
    v_today_high := v_row.today_has_high;
  ELSE
    v_today_low := v_row.today_has_low;
    v_today_high := TRUE;
  END IF;

  v_new_streak := v_row.current_streak;

  IF v_today_low AND v_today_high AND v_row.last_mutual_day IS DISTINCT FROM v_row.today_day THEN
    IF v_row.last_mutual_day = (v_row.today_day - INTERVAL '1 day')::date THEN
      v_new_streak := GREATEST(1, v_row.current_streak + 1);
    ELSE
      v_new_streak := 1;
    END IF;
  END IF;

  UPDATE public.love_streaks
  SET
    today_day = v_row.today_day,
    today_has_low = v_today_low,
    today_has_high = v_today_high,
    current_streak = CASE
      WHEN v_today_low AND v_today_high AND v_row.last_mutual_day IS DISTINCT FROM v_row.today_day
        THEN v_new_streak
      ELSE v_row.current_streak
    END,
    longest_streak = GREATEST(v_row.longest_streak, CASE
      WHEN v_today_low AND v_today_high AND v_row.last_mutual_day IS DISTINCT FROM v_row.today_day
        THEN v_new_streak
      ELSE v_row.current_streak
    END),
    last_mutual_day = CASE
      WHEN v_today_low AND v_today_high AND v_row.last_mutual_day IS DISTINCT FROM v_row.today_day
        THEN v_row.today_day
      ELSE v_row.last_mutual_day
    END,
    updated_at = timezone('utc'::text, now())
  WHERE user_low = v_low AND user_high = v_high;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_bump_love_streak_from_message ON public.messages;

CREATE TRIGGER trg_bump_love_streak_from_message
AFTER INSERT ON public.messages
FOR EACH ROW
EXECUTE FUNCTION public.bump_love_streak_from_message();
