-- 🎀 STICKER ARCHIVE: THƯ VIỆN BIỂU CẢM TIẾT KIÊM --

-- 1. Create Stickers Table (Nếu chưa có)
CREATE TABLE IF NOT EXISTS public.stickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Realtime for Stickers (Bỏ qua nếu bị lỗi 42710)
-- ALTER PUBLICATION supabase_realtime ADD TABLE stickers;

-- 3. Set up Row Level Security
ALTER TABLE public.stickers ENABLE ROW LEVEL SECURITY;

-- Cho phép mọi người xem nhãn dán (để chia sẻ niềm vui)
CREATE POLICY "Everyone can view stickers." ON public.stickers
  FOR SELECT USING (true);

-- Chỉ chủ nhân mới được thêm nhãn dán của mình
CREATE POLICY "Owners can insert their own stickers." ON public.stickers
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Chỉ chủ nhân mới được xóa nhãn dán của mình
CREATE POLICY "Owners can delete their own stickers." ON public.stickers
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
