-- -------------------------------------------------------------
-- ❤️ HEART INTERACTIONS: LƯU LẦN BẤM TIM GIỮA 2 NGƯỜI
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.heart_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES auth.users NOT NULL,
  receiver_id UUID REFERENCES auth.users NOT NULL,
  user_low UUID REFERENCES auth.users NOT NULL,
  user_high UUID REFERENCES auth.users NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT heart_interactions_pair_check CHECK (user_low <> user_high),
  CONSTRAINT heart_interactions_pair_order_check CHECK (user_low::text < user_high::text)
);

CREATE INDEX IF NOT EXISTS heart_interactions_pair_created_idx
  ON public.heart_interactions(user_low, user_high, created_at DESC);

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.heart_interactions;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_object THEN NULL;
END $$;

ALTER TABLE public.heart_interactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own heart interactions." ON public.heart_interactions;
DROP POLICY IF EXISTS "Users can insert own heart interactions." ON public.heart_interactions;

CREATE POLICY "Users can view own heart interactions." ON public.heart_interactions
  FOR SELECT TO authenticated
  USING (auth.uid() = user_low OR auth.uid() = user_high);

CREATE POLICY "Users can insert own heart interactions." ON public.heart_interactions
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = sender_id
    AND auth.uid() IN (user_low, user_high)
    AND receiver_id IN (user_low, user_high)
    AND sender_id <> receiver_id
  );
