-- 🏛️ SQL TO INFINITY: KIẾN TRÚC VĨNH CỬU CHO LOVECHAT --

-- 1. Create Profiles Table (Lưu trữ danh tính hai bạn)
-- Chỗ này lưu tên biệt danh, ảnh đại diện và thời gian cập nhật.
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Messages Table (Lưu trữ kỉ niệm vĩnh viễn)
-- Chỗ này lưu nội dung chat, link ảnh/sticker và thời gian gởi.
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES auth.users NOT NULL,
  content TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_read BOOLEAN DEFAULT FALSE
);

-- 3. Check & Enable Realtime (Dòng này có thể bỏ qua nếu đã chạy rồi)
-- Lệnh này cực kỳ quan trọng để tin nhắn nhảy lên ngay lập tức.
-- IF error occurs here (42710), simply ignore it, it means it's already active!
-- ALTER PUBLICATION supabase_realtime ADD TABLE messages;

-- 4. Set up Row Level Security (RLS - Bảo mật không gian riêng tư)
-- Đảm bảo không ai có thể xâm nhập vào hốc nhỏ bí mật của hai bạn.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Quyền đọc Profile: Cho phép hai bạn thấy tên/ảnh của nhau.
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

-- Quyền cập nhật Profile: Ai chỉ được sửa ảnh/tên của người đó.
CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Quyền đọc tin nhắn: Chỉ những người đã đăng nhập mới được đọc.
CREATE POLICY "Authenticated users can read messages." ON public.messages
  FOR SELECT TO authenticated USING (true);

-- Quyền gởi tin nhắn: Chỉ người đã đăng nhập mới được gởi dưới tên mình.
CREATE POLICY "Authenticated users can insert messages." ON public.messages
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = sender_id);
